/*
File: StartupProbeHarnesses.cpp
Purpose:
  Owns command-line early-exit probes that validate isolated startup subsystems.

Summary:
  Atlas generation, standalone physics/runtime-handle validation, and contact
  audio smoke execute before the ordinary window, renderer, worker, and Run
  owners are constructed.

Glossary:
  Early-exit probe: CLI mode that emits bounded evidence and returns a process
    exit code without entering the application loop.
  Runtime mirror: Scene/runtime stores that must retain the same typed physics
    handles as the public physics API.
  SDF (Signed Distance Field): Font-atlas representation generated by the atlas
    probe.

Invariants:
  - Output strings, output files, exit codes, and call positions are startup
    compatibility surface and remain byte-identical to the pre-split Init.cpp.
  - Probe state is local to one synchronous invocation and is never retained.
  - Physics and audio probes finish before ordinary runtime ownership begins.

Related:
  - StartupProbeHarnesses.h
  - StartupCommandLine.h
  - Agentic/Reports/2026-07-15/init-startup-decomposition-map.md
*/
#include "StartupProbeHarnesses.h"
#include "StartupCommandLine.h"
#include "../../Assets/AssetKeys.h"
#include "../../Core/Common.h"
#include "../../Core/Config.h"
#include "../../Physics/ColliderStore.h"
#include "../../Physics/PhysicsApi.h"
#include "../../Physics/PhysicsBodyStore.h"
#include "../../Rendering/RenderInstanceStore.h"
#include "../../Rendering/Text.h"
#include "../../World/WorldEnvironment.h"
#include "../Audio/ContactAudioService.h"
#include "../Scene/SceneController.h"
#include "../WindowConstants.h"
#include <cstdio>
#include <cstring>
#include <memory>
#include <string>
#include <vector>
#include <windows.h>
using namespace SkullbonezCore::Rendering;
using namespace SkullbonezCore::Physics;
namespace SkullbonezCore
{
namespace Runtime
{
namespace Startup
{
namespace
{
struct PhysicsRuntimeHandleSmokeResult
{
    bool passed = false;
    bool handlesMatchStores = false;
    bool renderMirrorMatches = false;
    bool jointUsesHandles = false;
    bool colliderRefreshMatches = false;
    bool reorderPreservesHandleState = false;
    bool failedCreationIsAtomic = false;
    bool deletionIsAtomic = false;
    bool mutationUsesStableHandle = false;
    int bodyCount = 0;
    int colliderCount = 0;
    int renderInstanceCount = 0;
    std::size_t pointJointCount = 0;
    PhysicsBodyHandle bodyA;
    std::string errorMessage;
};
PhysicsRuntimeHandleSmokeResult RunPhysicsRuntimeHandleSmokeSample()
{
    // Why: this smoke proves runtime-created bodies keep their returned physics
    // handles aligned with body/collider stores and render snapshots without opening the
    // window or renderer. WinMain runs the normal command-line/config bootstrap
    // before this helper so collection capacity uses the same config snapshot
    // as a regular runtime launch.
    // Lifetime: SceneController owns the validation-only physics and entity
    // stores exactly as it does during a normal scene. The cold smoke keeps the
    // owner off the launcher stack and executes once before steady gameplay.
    auto collection = std::make_unique<SkullbonezCore::Runtime::SceneController>();
    SkullbonezCore::Physics::PhysicsEngine& physics = collection->Physics();
    SkullbonezCore::Runtime::SceneEntityStore& sceneEntities = collection->Entities();
    PhysicsRuntimeHandleSmokeResult result;
    PhysicsBodyHandle createdBodies[2];
    for ( int i = 0; i < 2; ++i )
    {
        SkullbonezCore::Runtime::SceneEntityCreateDesc model;
        char name[32] = {};
        sprintf_s( name, sizeof( name ), "runtime_smoke_%d", i );
        model.SetName( name );
        PhysicsSceneObjectId sceneObjectId;
        sceneObjectId.value = static_cast<uint32_t>( i + 1 );
        model.sceneObjectId = sceneObjectId;
        const SkullbonezCore::Math::CollisionDetection::BoundingSphere shape(
            0.75f,
            SkullbonezCore::Math::Vector::Vector3( 0.0f, 0.0f, 0.0f ) );
        const auto appendResult = collection->TryCreateSceneEntity(
            std::move( model ),
            MakePhysicsBodyCreateDesc(
                sceneObjectId,
                shape,
                SkullbonezCore::Math::Vector::Vector3( static_cast<float>( i ) * 2.0f, 4.0f, 0.0f ),
                SkullbonezCore::Math::Orientation::IDENTITY_QUATERNION,
                SkullbonezCore::Math::Vector::Vector3( 0.0f, 0.0f, 0.0f ),
                SkullbonezCore::Math::Vector::Vector3( 0.0f, 0.0f, 0.0f ),
                SkullbonezCore::Math::Vector::Vector3( 1.0f, 1.0f, 1.0f ),
                2.0f + static_cast<float>( i ),
                0.0f,
                PhysicsBodyMotionKind::Dynamic,
                nullptr,
                name ),
            MakeColliderCreateDesc( shape, 0.0f, HashStr( "default" ) ) );
        if ( !appendResult.status.ok )
        {
            result.errorMessage = appendResult.status.error.message;
            return result;
        }
        createdBodies[i] = appendResult.body;
    }
    const int entityCountBeforeFailure = sceneEntities.Count();
    const int bodyCountBeforeFailure = collection->BodyStore().Count();
    const int colliderCountBeforeFailure = collection->Colliders().Count();
    const int renderCountBeforeFailure = collection->GetRenderInstanceStore().Count();
    const uint32_t descriptorCountBeforeFailure = physics.AuthoredBodyDescriptorCount().value;
    SkullbonezCore::Runtime::SceneEntityCreateDesc duplicateEntity;
    duplicateEntity.sceneObjectId = PhysicsSceneObjectId{ 1u };
    duplicateEntity.SetName( "runtime_smoke_duplicate" );
    const SkullbonezCore::Math::CollisionDetection::BoundingSphere duplicateShape(
        0.5f,
        SkullbonezCore::Math::Vector::Vector3( 0.0f, 0.0f, 0.0f ) );
    const auto duplicateResult = collection->TryCreateSceneEntity(
        std::move( duplicateEntity ),
        MakePhysicsBodyCreateDesc( PhysicsSceneObjectId{ 1u },
                                   duplicateShape,
                                   SkullbonezCore::Math::Vector::Vector3( 0.0f, 8.0f, 0.0f ),
                                   SkullbonezCore::Math::Orientation::IDENTITY_QUATERNION,
                                   SkullbonezCore::Math::Vector::Vector3( 0.0f, 0.0f, 0.0f ),
                                   SkullbonezCore::Math::Vector::Vector3( 0.0f, 0.0f, 0.0f ),
                                   SkullbonezCore::Math::Vector::Vector3( 1.0f, 1.0f, 1.0f ),
                                   1.0f,
                                   0.0f,
                                   PhysicsBodyMotionKind::Dynamic,
                                   nullptr,
                                   "runtime_smoke_duplicate" ),
        MakeColliderCreateDesc( duplicateShape, 0.0f, HashStr( "default" ) ) );
    const bool failedCreationIsAtomic = !duplicateResult.status.ok &&
                                        sceneEntities.Count() == entityCountBeforeFailure &&
                                        collection->BodyStore().Count() == bodyCountBeforeFailure &&
                                        collection->Colliders().Count() == colliderCountBeforeFailure &&
                                        collection->GetRenderInstanceStore().Count() == renderCountBeforeFailure &&
                                        physics.AuthoredBodyDescriptorCount().value == descriptorCountBeforeFailure;
    const PhysicsBodyHandle bodyA = createdBodies[0];
    const PhysicsBodyHandle bodyB = createdBodies[1];
    PhysicsPointJointCreateDesc jointDesc;
    jointDesc.bodyA = bodyA;
    jointDesc.bodyB = bodyB;
    jointDesc.localAnchorA = SkullbonezCore::Math::Vector::Vector3( 0.25f, 0.0f, 0.0f );
    jointDesc.localAnchorB = SkullbonezCore::Math::Vector::Vector3( -0.25f, 0.0f, 0.0f );
    const PhysicsConstraintHandle jointHandle = physics.CreatePointJoint( jointDesc );
    const PhysicsBodyStore& bodyStore = collection->BodyStore();
    const ColliderStore& colliderStore = collection->Colliders();
    const RenderInstanceStore& renderStore = collection->GetRenderInstanceStore();
    const std::vector<PointJointConstraint>& pointJoints =
        PhysicsEngine::ReadPointJointConstraints( collection->Physics() );
    const size_t initialColliderCount = colliderStore.Count();
    const ColliderRecord initialCollider = colliderStore.Records()[0];
    const SkullbonezCore::Math::Vector::Vector3 editedHalfExtents( 0.25f, 1.25f, 0.5f );
    constexpr float EDITED_RESTITUTION = 0.42f;
    PhysicsBodyUpdateDesc colliderUpdate;
    colliderUpdate.body = bodyA;
    const bool colliderUpdateAccepted = physics.UpdateAuthoredBodyAndCollider(
        colliderUpdate,
        MakeColliderCreateDesc( SkullbonezCore::Math::CollisionDetection::BoundingBox(
                                    editedHalfExtents,
                                    SkullbonezCore::Math::Vector::Vector3( 0.0f, 0.0f, 0.0f ) ),
                                EDITED_RESTITUTION,
                                HashStr( "default" ) ) );
    const ColliderStore& refreshedColliderStore = collection->Colliders();
    const ColliderRecord& refreshedCollider = refreshedColliderStore.Records()[0];
    const float expectedBoxRadius = sqrtf( 0.25f * 0.25f + 1.25f * 1.25f + 0.5f * 0.5f );
    // Invariant: same-count authoring edits must be visible through the explicit
    // collider edit commit. Store reads only auto-repair topology changes, so
    // tools and scene edits must commit before asking for collider records.
    const bool colliderRefreshMatches =
        colliderUpdateAccepted && initialCollider.shapeKind == ColliderShapeKind::Sphere &&
        refreshedCollider.shapeKind == ColliderShapeKind::Box &&
        fabsf( refreshedCollider.boundingRadius - expectedBoxRadius ) < 0.0001f &&
        fabsf( refreshedCollider.restitution - 0.42f ) < 0.0001f &&
        fabsf( refreshedCollider.projectedSurfaceArea - initialCollider.projectedSurfaceArea ) > 0.0001f &&
        fabsf( refreshedCollider.dragCoefficient - initialCollider.dragCoefficient ) > 0.0001f &&
        refreshedCollider.handle == initialCollider.handle && refreshedCollider.body == initialCollider.body &&
        refreshedColliderStore.Count() == initialColliderCount;
    const PhysicsBodyRecord* bodyARecord = bodyStore.RecordForModelIndex( 0 );
    const PhysicsBodyRecord* bodyBRecord = bodyStore.RecordForModelIndex( 1 );
    const RenderInstanceHandle renderHandleA = renderStore.HandleForModelIndex( 0 );
    const bool handlesMatchStores = bodyA.IsValid() && bodyB.IsValid() && bodyARecord && bodyBRecord &&
                                    bodyARecord->handle == bodyA && bodyBRecord->handle == bodyB &&
                                    colliderStore.HandleForBodyHandle( bodyA ).IsValid() &&
                                    colliderStore.HandleForBodyHandle( bodyB ).IsValid();
    const bool renderMirrorMatches = bodyARecord && renderStore.Count() == 2 && renderHandleA.IsValid() &&
                                     renderStore.ModelIndexForHandle( renderHandleA ) == 0 &&
                                     !renderStore.Records().empty() &&
                                     renderStore.Records()[0].replayBodyId == bodyARecord->replayBodyId;
    const bool jointUsesHandles = jointHandle.IsValid() && pointJoints.size() == 1 && pointJoints[0].bodyA == bodyA &&
                                  pointJoints[0].bodyB == bodyB && pointJoints[0].BodyAIndex( bodyStore ) == 0 &&
                                  pointJoints[0].BodyBIndex( bodyStore ) == 1;
    constexpr uint32_t REORDER_BODY_A_REPLAY_ID = 100u;
    constexpr uint32_t REORDER_BODY_B_REPLAY_ID = 101u;
    // Why: PhysicsBodyStore owns SkullbonezCore::Scene::Capacity::MAX_GAME_MODELS fixed arrays. Keep this cold
    // standalone probe owner off WinMain's bounded thread stack.
    auto reorderBodyStore = std::make_unique<PhysicsBodyStore>();
    std::vector<PhysicsBodyCreateDesc> reorderBodyDescs;
    for ( int i = 0; i < 2; ++i )
    {
        PhysicsBodyCreateDesc desc;
        desc.sceneObjectId =
            MakePhysicsSceneObjectIdFromReplayBodyId( REORDER_BODY_A_REPLAY_ID + static_cast<uint32_t>( i ) );
        desc.shape = SkullbonezCore::Math::CollisionDetection::BoundingSphere(
            0.5f,
            SkullbonezCore::Math::Vector::Vector3( 0.0f, 0.0f, 0.0f ) );
        desc.position = SkullbonezCore::Math::Vector::Vector3( static_cast<float>( i ) * 3.0f, 5.0f, 0.0f );
        desc.rotationalInertia = SkullbonezCore::Math::Vector::Vector3( 1.0f, 1.0f, 1.0f );
        desc.mass = 3.0f + static_cast<float>( i );
        desc.boundingRadius = SkullbonezCore::Math::CollisionDetection::GetShapeBoundingRadius( desc.shape );
        desc.volume = SkullbonezCore::Math::CollisionDetection::GetShapeVolume( desc.shape );
        desc.projectedSurfaceArea =
            SkullbonezCore::Math::CollisionDetection::GetShapeProjectedSurfaceArea( desc.shape );
        desc.dragCoefficient = SkullbonezCore::Math::CollisionDetection::GetShapeDragCoefficient( desc.shape );
        reorderBodyDescs.push_back( desc );
    }
    reorderBodyStore->LoadFromDescriptors( reorderBodyDescs, std::vector<uint8_t>{} );
    const PhysicsBodyHandle reorderedOriginalBody = reorderBodyStore->HandleForModelIndex( 0 );
    const uint32_t reorderBodyAReplayId = REORDER_BODY_A_REPLAY_ID;
    const uint32_t reorderBodyBReplayId = REORDER_BODY_B_REPLAY_ID;
    const SkullbonezCore::Math::Vector::Vector3 pendingImpulse( 0.0f, 2.0f, 0.0f );
    const SkullbonezCore::Math::Vector::Vector3 pendingImpulsePoint( 0.25f, 0.0f, 0.0f );
    const bool seededReorderState =
        reorderBodyStore->SetPendingBodyImpulse( reorderedOriginalBody, pendingImpulse, pendingImpulsePoint ) &&
        reorderBodyStore->SeedBodyAsleep( reorderedOriginalBody );
    reorderBodyDescs[0].sceneObjectId = MakePhysicsSceneObjectIdFromReplayBodyId( reorderBodyBReplayId );
    reorderBodyDescs[1].sceneObjectId = MakePhysicsSceneObjectIdFromReplayBodyId( reorderBodyAReplayId );
    reorderBodyStore->LoadFromDescriptors( reorderBodyDescs, std::vector<uint8_t>{} );
    const int reorderedBodyAIndex = reorderBodyStore->ModelIndexForHandle( reorderedOriginalBody );
    const PhysicsBodyRecord* reorderedBodyARecord =
        reorderedBodyAIndex >= 0 ? reorderBodyStore->RecordForModelIndex( reorderedBodyAIndex ) : nullptr;
    // Invariant: allocator-owned handles must carry physics-owned one-shot
    // state through a same-scene reorder. Otherwise the handle identity is only
    // nominally independent from model order.
    const bool reorderPreservesHandleState =
        seededReorderState && reorderedBodyAIndex == 1 && reorderedBodyARecord &&
        reorderedBodyARecord->handle == reorderedOriginalBody && reorderedBodyARecord->hasPendingImpulse &&
        reorderedBodyARecord->isSleeping &&
        fabsf( reorderedBodyARecord->pendingImpulse.y - pendingImpulse.y ) < 0.0001f &&
        fabsf( reorderedBodyARecord->pendingImpulseApplicationPoint.x - pendingImpulsePoint.x ) < 0.0001f;
    const PhysicsBodyRecord* bodyBBeforeDelete = collection->BodyStore().RecordForHandle( bodyB );
    const SkullbonezCore::Math::Vector::Vector3 liveOnlyPosition( 42.0f, 17.0f, -3.0f );
    const bool seededLiveOnlyState =
        bodyBBeforeDelete && physics.RestoreReplayBodyState( bodyB,
                                                             bodyBBeforeDelete->replayBodyId,
                                                             bodyBBeforeDelete->isFixed,
                                                             liveOnlyPosition,
                                                             bodyBBeforeDelete->orientation,
                                                             bodyBBeforeDelete->linearVelocity,
                                                             bodyBBeforeDelete->angularVelocity,
                                                             bodyBBeforeDelete->mass,
                                                             bodyBBeforeDelete->invMass,
                                                             bodyBBeforeDelete->rotationalInertia,
                                                             bodyBBeforeDelete->invRotationalInertia );
    const bool destroyedBodyA = collection->DestroySceneEntity( bodyA );
    const PhysicsBodyRecord* survivingBody = collection->BodyStore().RecordForHandle( bodyB );
    const bool deletionIsAtomic = seededLiveOnlyState && destroyedBodyA && !collection->BodyStore().Contains( bodyA ) &&
                                  survivingBody && collection->BodyStore().ModelIndexForHandle( bodyB ) == 0 &&
                                  sceneEntities.Count() == 1 && sceneEntities.At( 0 ).body == bodyB &&
                                  collection->BodyStore().Count() == 1 && collection->Colliders().Count() == 1 &&
                                  collection->Colliders().HandleForBodyHandle( bodyB ).IsValid() &&
                                  collection->GetRenderInstanceStore().Count() == 1 &&
                                  collection->GetRenderInstanceStore().PresentationCount() == 1 &&
                                  physics.AuthoredBodyDescriptorCount().value == 1u &&
                                  PhysicsEngine::ReadPointJointConstraints( collection->Physics() ).empty() &&
                                  fabsf( survivingBody->position.x - liveOnlyPosition.x ) < 0.0001f &&
                                  fabsf( survivingBody->position.y - liveOnlyPosition.y ) < 0.0001f &&
                                  fabsf( survivingBody->position.z - liveOnlyPosition.z ) < 0.0001f;
    PhysicsBodyUpdateDesc staleUpdate;
    staleUpdate.body = bodyA;
    staleUpdate.updateMask = PHYSICS_BODY_UPDATE_POSE;
    PhysicsBodyUpdateDesc survivingUpdate;
    survivingUpdate.body = bodyB;
    survivingUpdate.updateMask = PHYSICS_BODY_UPDATE_VELOCITY | PHYSICS_BODY_UPDATE_MASS;
    survivingUpdate.linearVelocity = SkullbonezCore::Math::Vector::Vector3( 2.0f, 3.0f, 4.0f );
    survivingUpdate.angularVelocity = SkullbonezCore::Math::Vector::Vector3( 0.0f, 0.5f, 0.0f );
    survivingUpdate.mass = 7.0f;
    survivingUpdate.rotationalInertia =
        survivingBody ? survivingBody->rotationalInertia : SkullbonezCore::Math::Vector::ZERO_VECTOR;
    const bool staleMutationRejected = !physics.UpdateAuthoredBody( staleUpdate );
    const bool survivingMutationAccepted = physics.UpdateAuthoredBody( survivingUpdate );
    survivingBody = collection->BodyStore().RecordForHandle( bodyB );
    const bool mutationUsesStableHandle = staleMutationRejected && survivingMutationAccepted && survivingBody &&
                                          fabsf( survivingBody->mass - 7.0f ) < 0.0001f &&
                                          fabsf( survivingBody->linearVelocity.x - 2.0f ) < 0.0001f &&
                                          fabsf( survivingBody->angularVelocity.y - 0.5f ) < 0.0001f;
    result.handlesMatchStores = handlesMatchStores;
    result.renderMirrorMatches = renderMirrorMatches;
    result.jointUsesHandles = jointUsesHandles;
    result.colliderRefreshMatches = colliderRefreshMatches;
    result.reorderPreservesHandleState = reorderPreservesHandleState;
    result.failedCreationIsAtomic = failedCreationIsAtomic;
    result.deletionIsAtomic = deletionIsAtomic;
    result.mutationUsesStableHandle = mutationUsesStableHandle;
    result.bodyCount = bodyCountBeforeFailure;
    result.colliderCount = colliderCountBeforeFailure;
    result.renderInstanceCount = renderCountBeforeFailure;
    result.pointJointCount = jointUsesHandles ? 1u : 0u;
    result.bodyA = bodyA;
    result.passed = handlesMatchStores && renderMirrorMatches && jointUsesHandles && colliderRefreshMatches &&
                    reorderPreservesHandleState && failedCreationIsAtomic && deletionIsAtomic &&
                    mutationUsesStableHandle;
    return result;
}
struct CliFlagDirective
{
    // Table-driven flag parsing keeps aliases beside the canonical spelling.
    // That matters because command-line options are user-facing compatibility
    // surface, not private implementation detail.
    const char* name;
    const char* alias;
    void ( *apply )( ParsedArgs& args );
    const char* message;
};
struct CliValueDirective
{
    const char* name;
    const char* alias;
    bool ( *apply )( const char* value, ParsedArgs& args );
};
bool HasFlagDirective( const CommandLineView& commandLine, const CliFlagDirective& directive )
{
    return HasOption( commandLine, directive.name ) || ( directive.alias && HasOption( commandLine, directive.alias ) );
}
bool ValidatePhysicsRegressionLog( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--physics-regression-log" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse( "--physics-regression-log is only supported in Debug builds. Recompile with the Debug "
                                 "configuration to use physics regression logging." );
#else
    return true;
#endif
}
bool ValidatePhysicsCollisionTimeLog( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--physics-collision-time-log" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse( "--physics-collision-time-log is only supported in Debug builds. Recompile with the "
                                 "Debug configuration to use collision-time logging." );
#else
    return true;
#endif
}
bool ValidatePhysicsDiagnostics( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--physics-diag" ) && !HasOption( commandLine, "--physics-diagnostics" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse( "--physics-diag is only supported in Debug builds. Recompile with the Debug "
                                 "configuration to use queryable physics diagnostics." );
#else
    return true;
#endif
}
bool ValidateReplayScrubProbe( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--replay-scrub-test" ) && !HasOption( commandLine, "--replay_scrub_test" ) &&
         !HasOption( commandLine, "--replay-scrub-probe" ) && !HasOption( commandLine, "--replay_scrub_probe" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse(
        "--replay-scrub-probe is only supported in Debug builds with SkullScope diagnostics." );
#else
    return true;
#endif
}
bool ValidateReplayRestoreProbe( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--replay-restore-test" ) && !HasOption( commandLine, "--replay_restore_test" ) &&
         !HasOption( commandLine, "--replay-restore-probe" ) && !HasOption( commandLine, "--replay_restore_probe" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse(
        "--replay-restore-probe is only supported in Debug builds with SkullScope diagnostics." );
#else
    return true;
#endif
}
bool ValidateReplaySaveProbe( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--replay-save-probe" ) && !HasOption( commandLine, "--replay_save_probe" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse( "--replay-save-probe is only supported in Debug builds." );
#else
    return true;
#endif
}
bool ValidateReplayLoadProbe( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--replay-load-probe" ) && !HasOption( commandLine, "--replay_load_probe" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse( "--replay-load-probe is only supported in Debug builds." );
#else
    return true;
#endif
}
bool ValidateReplayRestoreFileProbe( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--replay-restore-file-probe" ) &&
         !HasOption( commandLine, "--replay_restore_file_probe" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse( "--replay-restore-file-probe is only supported in Debug builds." );
#else
    return true;
#endif
}
bool ValidateReplayRestoreTargetFileProbe( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--replay-restore-target-file-probe" ) &&
         !HasOption( commandLine, "--replay_restore_target_file_probe" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse( "--replay-restore-target-file-probe is only supported in Debug builds." );
#else
    return true;
#endif
}
bool ValidateReplayRestoreBranchFileProbe( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--replay-restore-branch-file-probe" ) &&
         !HasOption( commandLine, "--replay_restore_branch_file_probe" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse( "--replay-restore-branch-file-probe is only supported in Debug builds." );
#else
    return true;
#endif
}
bool ValidateReplayRestoreFailureFileProbe( const CommandLineView& commandLine )
{
    if ( !HasOption( commandLine, "--replay-restore-failure-file-probe" ) &&
         !HasOption( commandLine, "--replay_restore_failure_file_probe" ) )
    {
        return true;
    }
#ifndef _DEBUG
    return FailCommandLineParse( "--replay-restore-failure-file-probe is only supported in Debug builds." );
#else
    if ( !HasOption( commandLine, "--physics-diag" ) && !HasOption( commandLine, "--physics-diagnostics" ) )
    {
        return FailCommandLineParse(
            "--replay-restore-failure-file-probe requires --physics-diag so SkullScope can query the failure row." );
    }
    return true;
#endif
}
bool ParsePhysicsRegressionLogOverride( const CommandLineView& commandLine, char ( &outPath )[256] )
{
    outPath[0] = '\0';
    const char* physLogArg = FindOptionValue( commandLine, "--physics-regression-log" );
    if ( !physLogArg )
    {
        return true;
    }
    if ( !CopyCommandLinePath( physLogArg, "--physics-regression-log", outPath, sizeof( outPath ) ) )
    {
        return false;
    }
    fprintf( stdout, "[physics-regression-log] Output: %s\n", outPath );
    return true;
}
bool ParsePhysicsCollisionTimeLogOverride( const CommandLineView& commandLine, char ( &outPath )[256] )
{
    outPath[0] = '\0';
    const char* collisionLogArg = FindOptionValue( commandLine, "--physics-collision-time-log" );
    if ( !collisionLogArg )
    {
        return true;
    }
    if ( !CopyCommandLinePath( collisionLogArg, "--physics-collision-time-log", outPath, sizeof( outPath ) ) )
    {
        return false;
    }
    fprintf( stdout, "[physics-collision-time-log] Output: %s\n", outPath );
    return true;
}
bool ParsePhysicsDiagnosticsPath( const CommandLineView& commandLine, char ( &outPath )[256] )
{
    outPath[0] = '\0';
    const char* diagArg = FindOptionValue( commandLine, "--physics-diag" );
    if ( !diagArg )
    {
        diagArg = FindOptionValue( commandLine, "--physics-diagnostics" );
    }
    if ( !diagArg )
    {
        return true;
    }
    return CopyCommandLinePath( diagArg, "--physics-diag", outPath, sizeof( outPath ) );
}
} // anonymous namespace
bool HandleGenAtlas( const CommandLineView& commandLine, int& outExitCode )
{
    if ( !HasOption( commandLine, "--gen-atlas" ) )
    {
        return false;
    }
    char outPath[MAX_PATH];
    const char* atlasArg = FindOptionValue( commandLine, "--gen-atlas" );
    if ( atlasArg && *atlasArg != '\0' )
    {
        if ( strlen( atlasArg ) >= MAX_PATH )
        {
            fprintf( stderr, "[gen-atlas] Output path is too long.\n" );
            outExitCode = 1;
            return true;
        }
        strcpy_s( outPath, atlasArg );
    }
    else
    {
        strcpy_s( outPath, "SkullbonezData/font_atlas.sdf" );
    }
    fprintf( stdout, "[gen-atlas] Generating SDF font atlas: %s\n", outPath );
    if ( SkullbonezCore::Text::Text2d::GenerateSdfAtlasToFile( "Verdana", outPath ) )
    {
        fprintf( stdout, "[gen-atlas] Done.\n" );
        outExitCode = 0;
    }
    else
    {
        fprintf( stderr, "[gen-atlas] FAILED.\n" );
        outExitCode = 1;
    }
    return true;
}
bool HandlePhysicsStandaloneSmoke( const CommandLineView& commandLine, int& outExitCode )
{
    if ( !HasOption( commandLine, "--physics-standalone-smoke" ) &&
         !HasOption( commandLine, "--physics_standalone_smoke" ) )
    {
        return false;
    }
    // Why: this option runs before WorkerPool, Window, renderer, Run, or scene
    // setup so it proves the public physics API and runtime handle alignment can
    // be constructed without renderer/window services.
    const PhysicsStandaloneSmokeResult result = RunPhysicsStandaloneSmoke();
    PhysicsRuntimeHandleSmokeResult runtimeMirror = RunPhysicsRuntimeHandleSmokeSample();
    auto writeReport = [&]( FILE* stream )
    {
        if ( !stream )
        {
            return;
        }
        fprintf( stream,
                 "[physics-standalone-smoke] bodies=%u steps=%u final_position=(%.6f,%.6f,%.6f) "
                 "final_velocity=(%.6f,%.6f,%.6f) secondary_position=(%.6f,%.6f,%.6f) "
                 "secondary_velocity=(%.6f,%.6f,%.6f) secondary_step=%s lifecycle_checks=%s "
                 "contacts=%u contact_hash=0x%016llX runtime_mirror_checks=%s hash=0x%016llX\n",
                 result.bodyCount,
                 result.stepCount,
                 result.finalPosition.x,
                 result.finalPosition.y,
                 result.finalPosition.z,
                 result.finalLinearVelocity.x,
                 result.finalLinearVelocity.y,
                 result.finalLinearVelocity.z,
                 result.secondaryFinalPosition.x,
                 result.secondaryFinalPosition.y,
                 result.secondaryFinalPosition.z,
                 result.secondaryFinalLinearVelocity.x,
                 result.secondaryFinalLinearVelocity.y,
                 result.secondaryFinalLinearVelocity.z,
                 result.secondaryBodyAdvanced ? "pass" : "fail",
                 result.lifecycleChecksPassed ? "pass" : "fail",
                 result.contactCount,
                 static_cast<unsigned long long>( result.contactHash ),
                 runtimeMirror.passed ? "pass" : "fail",
                 static_cast<unsigned long long>( result.deterministicHash ) );
        fprintf( stream,
                 "[physics-runtime-handle-smoke] bodies=%d colliders=%d render_instances=%d point_joints=%zu "
                 "handle_a=(%u,%u) store_handles=%s render_mirror=%s joint_handles=%s collider_refresh=%s "
                 "reorder_state=%s creation_atomic=%s deletion_atomic=%s mutation_handle=%s\n",
                 runtimeMirror.bodyCount,
                 runtimeMirror.colliderCount,
                 runtimeMirror.renderInstanceCount,
                 runtimeMirror.pointJointCount,
                 runtimeMirror.bodyA.index,
                 runtimeMirror.bodyA.generation,
                 runtimeMirror.handlesMatchStores ? "pass" : "fail",
                 runtimeMirror.renderMirrorMatches ? "pass" : "fail",
                 runtimeMirror.jointUsesHandles ? "pass" : "fail",
                 runtimeMirror.colliderRefreshMatches ? "pass" : "fail",
                 runtimeMirror.reorderPreservesHandleState ? "pass" : "fail",
                 runtimeMirror.failedCreationIsAtomic ? "pass" : "fail",
                 runtimeMirror.deletionIsAtomic ? "pass" : "fail",
                 runtimeMirror.mutationUsesStableHandle ? "pass" : "fail" );
        if ( !runtimeMirror.errorMessage.empty() )
        {
            fprintf( stream, "[physics-runtime-handle-smoke] error=\"%s\"\n", runtimeMirror.errorMessage.c_str() );
        }
        fflush( stream );
    };
    writeReport( stdout );
    const char* reportPath =
        FindOptionValue( commandLine, "--physics-standalone-smoke-log", "--physics_standalone_smoke_log" );
    if ( reportPath && !IsOptionValueMissing( reportPath ) )
    {
        FILE* reportFile = nullptr;
        if ( fopen_s( &reportFile, reportPath, "w" ) == 0 && reportFile )
        {
            writeReport( reportFile );
            fclose( reportFile );
        }
    }
    if ( !result.passed || !runtimeMirror.passed )
    {
        fprintf( stderr,
                 "FAIL: physics smoke final state, lifecycle, or runtime mirror checks did not match the expected "
                 "sample.\n" );
        outExitCode = 1;
        return true;
    }
    fprintf( stdout, "PASS: standalone physics and runtime handle mirror smoke matched expected state.\n" );
    outExitCode = 0;
    return true;
}
bool HandleContactAudioSmoke( const ParsedArgs& args, const SkullbonezCore::Core::EngineConfig& cfg, int& outExitCode )
{
    if ( !args.contactAudioSmoke )
    {
        return false;
    }
    // Concept: this smoke path proves decode, voice submission, and counters
    // without creating a window, renderer, worker pool, or physics world.
    SkullbonezCore::Runtime::Audio::ContactAudioService audio;
    audio.SetMasterGain( cfg.contactAudio.masterGain );
    audio.SetMaxDistanceScale( cfg.contactAudio.maxDistanceScale );
    audio.SetRollingLevelDb( cfg.contactAudio.rollingLevelDb );
    audio.SetRollingMaxDistance( cfg.contactAudio.rollingMaxDistance );
    audio.SetRollingMinSlipSpeed( cfg.contactAudio.rollingMinSlipSpeed );
    audio.SetRollingVoicesPerWindow( static_cast<uint32_t>( cfg.contactAudio.rollingVoicesPerWindow ) );
    const bool initialized = audio.Initialize();
    const bool loaded = audio.LoadContactAudioMap( "SkullbonezData/audio/contact_audio.materials.json" );
    const bool submitted = initialized && loaded && audio.PlaySmokeImpact( HashStr( "earth" ), 6.0f );
    Sleep( 350 );
    const SkullbonezCore::Runtime::Audio::ContactAudioStats& stats = audio.Stats();
    CreateDirectoryA( "TestOutput", nullptr );
    FILE* report = nullptr;
    if ( fopen_s( &report, "TestOutput/contact_audio_smoke.json", "w" ) == 0 && report )
    {
        fprintf( report,
                 "{\n"
                 "  \"initialized\": %s,\n"
                 "  \"loaded\": %s,\n"
                 "  \"submitted\": %s,\n"
                 "  \"eventsSeen\": %u,\n"
                 "  \"rejectedByThreshold\": %u,\n"
                 "  \"rejectedByCooldown\": %u,\n"
                 "  \"submittedVoices\": %u,\n"
                 "  \"droppedVoices\": %u\n"
                 "}\n",
                 initialized ? "true" : "false",
                 loaded ? "true" : "false",
                 submitted ? "true" : "false",
                 stats.eventsSeen,
                 stats.rejectedByThreshold,
                 stats.rejectedByCooldown,
                 stats.submittedVoices,
                 stats.droppedVoices );
        fclose( report );
    }
    fprintf( stdout,
             "[audio-smoke] initialized=%d loaded=%d submitted=%d events=%u threshold=%u cooldown=%u voices=%u "
             "dropped=%u report=TestOutput/contact_audio_smoke.json\n",
             initialized ? 1 : 0,
             loaded ? 1 : 0,
             submitted ? 1 : 0,
             stats.eventsSeen,
             stats.rejectedByThreshold,
             stats.rejectedByCooldown,
             stats.submittedVoices,
             stats.droppedVoices );
    fflush( stdout );
    outExitCode = submitted ? 0 : 1;
    return true;
}
void ApplyProbeFlagDirectives( const CommandLineView& commandLine, ParsedArgs& out )
{
    static const CliFlagDirective kFlags[] = {
        { "--fixed-step",
          nullptr,
          []( ParsedArgs& args ) { args.fixedStep = true; },
          "[fixed-step] Forced via command line." },
        { "--no-water",
          nullptr,
          []( ParsedArgs& args ) { args.noWater = true; },
          "[water] Fluid surface starts below terrain." },
        { "--no-sleep",
          nullptr,
          []( ParsedArgs& args ) { args.noSleep = true; },
          "[physics] Sleep disabled via command line." },
        { "--no-contact-audio",
          "--mute-contact-audio",
          []( ParsedArgs& args ) { args.noContactAudio = true; },
          "[audio] Contact impact audio disabled." },
        { "--contact-audio-smoke",
          "--audio-smoke",
          []( ParsedArgs& args )
          {
              args.contactAudioSmoke = true;
              args.suppressExitDialog = true;
          },
          "[audio] Contact audio standalone smoke requested." },
        { "--scene-load-only",
          "--load-scenes-only",
          []( ParsedArgs& args )
          {
              args.sceneLoadOnly = true;
              args.suppressExitDialog = true;
          },
          "[scene-load-only] Load queued scenes without running frames." },
        { "--demohero",
          "--demo-hero",
          []( ParsedArgs& args )
          {
              args.demoHeroStyle = true;
              args.suppressExitDialog = true;
          },
          "[scene] Generated demo scene will use the low-poly hero rendering mode." },
        { "--profiler",
          "--show-profiler",
          []( ParsedArgs& args ) { args.showProfiler = true; },
          "[overlay] SkullbonezCore::Core::Profiler HUD enabled at startup." },
        { "--platform-profiler-markers",
          "--platform-profiler",
          []( ParsedArgs& args )
          {
              args.platformProfilerMarkers = true;
              args.platformProfilerMarkersExplicit = true;
          },
          "[platform-profiler] Platform profiler marker emission requested." },
        { "--pix-markers",
          "--pix",
          []( ParsedArgs& args )
          {
              args.platformProfilerMarkers = true;
              args.platformProfilerMarkersExplicit = true;
          },
          "[platform-profiler] PIX marker compatibility alias requested." },
        { "--hide-top-text",
          "--no-top-text",
          []( ParsedArgs& args ) { args.hideTopText = true; },
          "[overlay] Top HUD text hidden." },
        { "--automation-hidden-window",
          nullptr,
          []( ParsedArgs& args )
          {
              args.automationWindowHidden = true;
              args.suppressExitDialog = true;
          },
          "[automation] Native window hidden; DX12 rendering and capture remain active." },
        { "--broadphase-visualizer",
          "--broadphase-overlay",
          []( ParsedArgs& args ) { args.showBroadphaseVisualizer = true; },
          "[overlay] Broadphase visualizer enabled at startup." },
        { "--dump-config", nullptr, []( ParsedArgs& args ) { args.dumpConfig = true; }, nullptr },
        { "--dump-assets", nullptr, []( ParsedArgs& args ) { args.dumpAssets = true; }, nullptr },
        { "--replay-scrub-test",
          "--replay_scrub_test",
          []( ParsedArgs& args )
          {
              args.replayScrubProbe = true;
              args.replayScrubProbeNormalized = 0.25f;
              args.replayRecording = true;
              args.replayExplicit = true;
              args.replaySeconds = 1;
              args.fixedStep = true;
              args.suppressExitDialog = true;
          },
          "[replay] Scrub SkullScope probe enabled." },
        { "--replay-restore-test",
          "--replay_restore_test",
          []( ParsedArgs& args )
          {
              args.replayRestoreProbe = true;
              args.replayRestoreProbeNormalized = 0.25f;
              args.replayRecording = true;
              args.replayExplicit = true;
              args.replaySeconds = 1;
              args.fixedStep = true;
              args.suppressExitDialog = true;
          },
          "[replay] Restore hash SkullScope probe enabled." },
        { "--worker-self-test",
          "--workers-self-test",
          []( ParsedArgs& args )
          {
              args.workerSelfTest = true;
              args.suppressExitDialog = true;
          },
          "[workers] Self-test requested." },
    };
    for ( const CliFlagDirective& flag : kFlags )
    {
        if ( HasFlagDirective( commandLine, flag ) )
        {
            flag.apply( out );
            if ( flag.message )
            {
                fprintf( stdout, "%s\n", flag.message );
            }
        }
    }
}
bool ValidateProbeCommandLineOptions( const CommandLineView& commandLine, ParsedArgs& out )
{
    if ( !ValidatePhysicsRegressionLog( commandLine ) || !ValidatePhysicsCollisionTimeLog( commandLine ) ||
         !ValidatePhysicsDiagnostics( commandLine ) || !ValidateReplayScrubProbe( commandLine ) ||
         !ValidateReplayRestoreProbe( commandLine ) || !ValidateReplaySaveProbe( commandLine ) ||
         !ValidateReplayLoadProbe( commandLine ) || !ValidateReplayRestoreFileProbe( commandLine ) ||
         !ValidateReplayRestoreTargetFileProbe( commandLine ) || !ValidateReplayRestoreBranchFileProbe( commandLine ) ||
         !ValidateReplayRestoreFailureFileProbe( commandLine ) )
    {
        return false;
    }
#ifdef _DEBUG
    if ( !ParsePhysicsRegressionLogOverride( commandLine, out.physicsRegressionLogOverride ) ||
         !ParsePhysicsCollisionTimeLogOverride( commandLine, out.physicsCollisionTimeLogOverride ) ||
         !ParsePhysicsDiagnosticsPath( commandLine, out.physicsDiagnosticsPath ) )
    {
        return false;
    }
    out.physicsDiagnosticsRequested = out.physicsDiagnosticsPath[0] != '\0';
#else
    (void)out;
#endif
    return true;
}
} // namespace Startup
} // namespace Runtime
} // namespace SkullbonezCore
