/*
File: SkullbonezSource/SkullbonezCollisionVisualizer.cpp
Purpose:
  Builds debug drawing for collision shapes and contact diagnostics.

Mental model:
  Physics is deterministic fixed-step state update. Units, contact ownership,
  solver stages, sleep policy, and baseline-sensitive behavior are the key
  reading anchors.

Glossary:
  GPU (Graphics Processing Unit): Processor that executes rendering, compute,
  and raytracing commands asynchronously from the CPU.
  Broadphase: Cheap collision pass that finds object pairs worth testing more
  precisely.
  Narrowphase: Precise collision pass that computes contact points, normals,
  and penetration.
  Manifold: Set of contact points and normals describing one colliding pair.

Invariants:
  - Physics-visible behavior must remain deterministic; byte-exact baselines
  are the validation contract.

Related:
  - SkullbonezSource/SkullbonezCollisionVisualizer.h
  - Agentic/Reference/physics-overview.md
  - Agentic/Reference/comment-style-guide.md
*/
// =============================================================================
// COLLISION VISUALIZER (SkullbonezCollisionVisualizer.cpp)
// =============================================================================
//
// Debug renderer for the V-key collision/sleep-state view.
//
// This path deliberately stays separate from normal textured model rendering:
//   - normal rendering draws material-like balls and boxes;
//   - collision visualization draws the same collision volumes with state colors.
//
// The primitive coordinates are shared through SkullbonezPrimitiveMeshBuilder.h so
// sphere tessellation, box winding, and local orientation cannot drift between the
// two renderers. GPU resources, shaders, and instance payloads remain separate
// because this renderer needs a per-instance color in addition to each model matrix.
// =============================================================================


#include "SkullbonezCollisionVisualizer.h"
#include "SkullbonezGameModelCollection.h"
#include "SkullbonezGameModel.h"
#include "SkullbonezIRenderBackend.h"
#include "SkullbonezPrimitiveMeshBuilder.h"
#include "SkullbonezCommon.h"

#include <algorithm>


using namespace SkullbonezCore::Physics;
using namespace SkullbonezCore::GameObjects;
using namespace SkullbonezCore::Math::Transformation;
using namespace SkullbonezCore::Rendering;


CollisionVisualizer::~CollisionVisualizer()
{
    ResetResources();
}


void CollisionVisualizer::SetClipPlane( float x, float y, float z, float w )
{
    // The render loop uses this during water reflection passes so the debug solids
    // obey the same reflection clipping as the normal model renderer.
    m_clipPlane[0] = x;
    m_clipPlane[1] = y;
    m_clipPlane[2] = z;
    m_clipPlane[3] = w;
}


void CollisionVisualizer::SetAlphaOverride( float alpha )
{
    m_alphaOverride = alpha;
}


void CollisionVisualizer::ResetResources()
{
    // Backend resources are context/device-owned. When the renderer is recreated,
    // drop the cached handles and lazily rebuild them the next time Render() runs.
    m_shader.reset();
    if ( IsGfxReady() )
    {
        if ( m_sphereInstMesh )
        {
            Gfx().DestroyInstancedMesh( m_sphereInstMesh );
        }
        if ( m_boxInstMesh )
        {
            Gfx().DestroyInstancedMesh( m_boxInstMesh );
        }
    }
    m_sphereInstMesh = 0;
    m_boxInstMesh = 0;
    m_sphereVertexCount = 0;
    m_boxVertexCount = 0;
}


void CollisionVisualizer::BuildSphereMesh()
{
    // The collision shader only reads position and normal from the static vertex
    // buffer. UVs are generated by the shared primitive builder for the normal
    // renderer, then intentionally dropped here.
    constexpr int slices = 25;
    constexpr int stacks = 25;
    std::vector<float> verts;
    verts.reserve( PrimitiveMeshes::SphereTriangleVertexCount( slices, stacks ) * 6 );

    PrimitiveMeshes::EmitUnitSphere( slices, stacks, [&]( const PrimitiveMeshes::VertexPNUV& vertex )
                                     { verts.insert( verts.end(), { vertex.x, vertex.y, vertex.z, vertex.nx, vertex.ny, vertex.nz } ); } );

    m_sphereVertexCount = PrimitiveMeshes::SphereTriangleVertexCount( slices, stacks );

    // Static attributes occupy shader locations 0-1: position and normal.
    // Instance attributes start at location 3, leaving location 2 unused so the
    // layout stays compatible with the normal renderer's position/normal/uv slots.
    int staticAttribSizes[] = { 3, 3 };
    int instanceAttribSizes[] = { 4, 4, 4, 4, 4 };
    m_sphereInstMesh = Gfx().CreateInstancedMesh( verts.data(), m_sphereVertexCount, 6, MAX_GAME_MODELS, INSTANCE_FLOATS, 3, instanceAttribSizes, 5, staticAttribSizes, 2 );
}


void CollisionVisualizer::BuildBoxMesh()
{
    // Same shared unit cube as SkullbonezHelper::BuildBoxMesh(), packed for the
    // collision shader's smaller static layout: position plus face normal.
    std::vector<float> verts;
    verts.reserve( PrimitiveMeshes::BoxTriangleVertexCount() * 6 );

    PrimitiveMeshes::EmitUnitBox( [&]( const PrimitiveMeshes::VertexPNUV& vertex )
                                  { verts.insert( verts.end(), { vertex.x, vertex.y, vertex.z, vertex.nx, vertex.ny, vertex.nz } ); } );

    m_boxVertexCount = PrimitiveMeshes::BoxTriangleVertexCount();

    // Instance layout is mat4 + rgba:
    //   locations 3-6: model matrix columns
    //   location 7:    debug color
    int staticAttribSizes[] = { 3, 3 };
    int instanceAttribSizes[] = { 4, 4, 4, 4, 4 };
    m_boxInstMesh = Gfx().CreateInstancedMesh( verts.data(), m_boxVertexCount, 6, MAX_GAME_MODELS, INSTANCE_FLOATS, 3, instanceAttribSizes, 5, staticAttribSizes, 2 );
}


void CollisionVisualizer::EnsureResources()
{
    // Resource creation is lazy so toggling the visualizer off has no startup cost.
    // The shader and both primitive meshes are created together on the first visible
    // frame, then reused until ResetResources() is called.
    if ( !m_shader )
    {
        m_shader = Gfx().CreateShader( "shaders/collision_visualizer" );
    }
    if ( m_sphereInstMesh == 0 )
    {
        BuildSphereMesh();
    }
    if ( m_boxInstMesh == 0 )
    {
        BuildBoxMesh();
    }
}


void CollisionVisualizer::AppendInstance( std::vector<float>& out, const Matrix4& model, const Color& color )
{
    // The instance buffer is a tightly packed stream of:
    //   16 floats: model matrix
    //    4 floats: rgba debug color
    //
    // Render() builds separate sphere and box streams because each shape has its
    // own static mesh handle but the same instance payload format.
    const float* md = model.Data();
    out.insert( out.end(), md, md + 16 );
    out.push_back( color.r );
    out.push_back( color.g );
    out.push_back( color.b );
    out.push_back( color.a );
}


void CollisionVisualizer::Update( float dt, GameModelCollection& models )
{
    // This mirrors per-frame contact/sleep state into a visual fade cache. The
    // cache is for rendering only; the solver never reads these values back.
    // GameModelCollection records whether each object contacted another object
    // during the current physics step. This visualizer keeps a small amount of
    // temporal state so contact flashes do not disappear in a single frame.
    //
    // Color state:
    //   sleeping object: collision flash forced to zero; sleep palette wins
    //   contact object:  collision amount snaps to 1.0
    //   otherwise:       collision amount fades back toward 0.0 over FADE_DURATION
    const int modelCount = models.GetModelCount();
    if ( static_cast<int>( m_models.size() ) != modelCount )
    {
        m_models.assign( modelCount, TrackedModel() );
    }

    const std::vector<uint8_t>& contacts = models.GetCollisionVisualContacts();
    const std::vector<uint8_t>& sleepStates = models.GetSleepStates();
    const float fadeStep = ( FADE_DURATION > 0.0f ) ? ( dt / FADE_DURATION ) : 1.0f;

    for ( int i = 0; i < modelCount; ++i )
    {
        const bool sleeping = i < static_cast<int>( sleepStates.size() ) && sleepStates[i] != 0;
        const bool contact = i < static_cast<int>( contacts.size() ) && contacts[i] != 0;

        if ( sleeping )
        {
            m_models[i].collisionAmount = 0.0f;
        }
        else if ( contact )
        {
            m_models[i].collisionAmount = 1.0f;
        }
        else
        {
            m_models[i].collisionAmount = (std::max)( 0.0f, m_models[i].collisionAmount - fadeStep );
        }
    }
}


void CollisionVisualizer::BuildSleepGroupSizes( GameModelCollection& models )
{
    // Sleeping objects are grouped into islands by the solver. The color palette
    // uses that island id so stacks/resting piles are easy to distinguish at a
    // glance. Group size is also used for a special single-sphere color below.
    const int modelCount = models.GetModelCount();
    m_sleepGroupSizes.assign( modelCount, 1 );

    const std::vector<uint8_t>& sleepStates = models.GetSleepStates();
    const std::vector<int>& islandIds = models.GetSleepIslandVisualIds();

    for ( int i = 0; i < modelCount; ++i )
    {
        if ( i >= static_cast<int>( sleepStates.size() ) || sleepStates[i] == 0 )
        {
            continue;
        }

        const int islandId = i < static_cast<int>( islandIds.size() ) ? islandIds[i] : 0;
        int count = 0;
        for ( int j = 0; j < modelCount; ++j )
        {
            if ( j >= static_cast<int>( sleepStates.size() ) || sleepStates[j] == 0 )
            {
                continue;
            }

            const int otherIslandId = j < static_cast<int>( islandIds.size() ) ? islandIds[j] : 0;
            if ( islandId != 0 ? otherIslandId == islandId : j == i )
            {
                ++count;
            }
        }
        m_sleepGroupSizes[i] = (std::max)( 1, count );
    }
}


CollisionVisualizer::Color CollisionVisualizer::ComputeModelColor( int modelIndex, GameModelCollection& models ) const
{
    // Awake objects fade between green and red:
    //   green = no recent contact
    //   red   = contact this frame or still fading from one
    //
    // Sleeping objects use a separate palette by sleep island so stable groups are
    // visible even when they are no longer generating active contact flashes.
    static constexpr Color green = { 0.05f, 0.78f, 0.18f, 1.0f };
    static constexpr Color red = { 1.0f, 0.05f, 0.02f, 1.0f };
    static constexpr Color yellow = { 1.0f, 0.86f, 0.05f, 1.0f };
    static constexpr Color sleepingPalette[3] = {
        { 0.52f, 0.22f, 0.95f, 1.0f },
        { 1.0f, 0.22f, 0.67f, 1.0f },
        { 0.05f, 0.42f, 1.0f, 1.0f },
    };

    const std::vector<uint8_t>& sleepStates = models.GetSleepStates();
    const bool sleeping = modelIndex < static_cast<int>( sleepStates.size() ) && sleepStates[modelIndex] != 0;
    if ( sleeping )
    {
        GameModel& model = models.GetModelAtIndex( modelIndex );
        if ( !model.IsBox() && modelIndex < static_cast<int>( m_sleepGroupSizes.size() ) && m_sleepGroupSizes[modelIndex] <= 1 )
        {
            return yellow;
        }

        const std::vector<int>& islandIds = models.GetSleepIslandVisualIds();
        const int islandId = modelIndex < static_cast<int>( islandIds.size() ) && islandIds[modelIndex] != 0 ? islandIds[modelIndex] : modelIndex + 1;
        return sleepingPalette[( islandId - 1 ) % 3];
    }

    const float t = modelIndex < static_cast<int>( m_models.size() ) ? m_models[modelIndex].collisionAmount : 0.0f;
    return {
        green.r + ( red.r - green.r ) * t,
        green.g + ( red.g - green.g ) * t,
        green.b + ( red.b - green.b ) * t,
        1.0f,
    };
}


void CollisionVisualizer::DrawInstances( uint32_t mesh, int vertexCount, const std::vector<float>& instanceData )
{
    // Skip empty shape batches. This keeps mixed scenes cheap when one primitive
    // type is absent, and it avoids uploading an empty instance buffer.
    const int instanceCount = static_cast<int>( instanceData.size() ) / INSTANCE_FLOATS;
    if ( mesh == 0 || vertexCount <= 0 || instanceCount <= 0 )
    {
        return;
    }

    Gfx().UploadInstanceData( mesh, instanceData.data(), static_cast<int>( instanceData.size() ) );
    Gfx().DrawInstancedMesh( mesh, vertexCount, instanceCount );
}


void CollisionVisualizer::Render( GameModelCollection& models, const Matrix4& view, const Matrix4& proj, const float lightPos[4] )
{
    if ( !m_enabled || models.GetModelCount() <= 0 )
    {
        return;
    }

    EnsureResources();
    BuildSleepGroupSizes( models );

    m_sphereInstanceData.clear();
    m_boxInstanceData.clear();

    // Build per-shape instance streams from the authoritative collision shape
    // transform. This is the same model matrix normal rendering uses, so sphere
    // radius and box half-extents match the real simulation volumes.
    const int modelCount = models.GetModelCount();
    for ( int i = 0; i < modelCount; ++i )
    {
        GameModel& model = models.GetModelAtIndex( i );
        Color color = ComputeModelColor( i, models );
        if ( m_alphaOverride >= 0.0f )
        {
            color.a = m_alphaOverride;
        }
        if ( model.IsBox() )
        {
            AppendInstance( m_boxInstanceData, model.GetModelMatrix(), color );
        }
        else
        {
            AppendInstance( m_sphereInstanceData, model.GetModelMatrix(), color );
        }
    }

    // The fragment shader expects light position in view space. Keep the same
    // transform used by the normal lit path so collision solids respond to camera
    // movement and directional/positional light modes consistently.
    float viewLightPos[4];
    for ( int i = 0; i < 3; ++i )
    {
        viewLightPos[i] = view.m[i] * lightPos[0] + view.m[i + 4] * lightPos[1] + view.m[i + 8] * lightPos[2] + view.m[i + 12] * lightPos[3];
    }
    viewLightPos[3] = lightPos[3];

    m_shader->Use();
    m_shader->SetMat4( "uView", view );
    m_shader->SetMat4( "uProjection", proj );
    m_shader->SetVec4( "uClipPlane", m_clipPlane[0], m_clipPlane[1], m_clipPlane[2], m_clipPlane[3] );
    m_shader->SetVec4( "uLightPosition", viewLightPos[0], viewLightPos[1], viewLightPos[2], viewLightPos[3] );

    const bool translucent = m_alphaOverride >= 0.0f && m_alphaOverride < 1.0f;
    Gfx().SetBlend( translucent );
    if ( translucent )
    {
        Gfx().SetBlendFunc( BlendFactor::SrcAlpha, BlendFactor::OneMinusSrcAlpha );
        Gfx().SetDepthWrite( false );
    }
    DrawInstances( m_sphereInstMesh, m_sphereVertexCount, m_sphereInstanceData );
    DrawInstances( m_boxInstMesh, m_boxVertexCount, m_boxInstanceData );
    if ( translucent )
    {
        Gfx().SetDepthWrite( true );
    }
    Gfx().SetBlend( false );
}
