#!/usr/bin/env python3
"""
File: bake_shaders.py
Purpose:
  Compiles every shipping raster and compute shader to checked-in DXIL and
  maintains the deterministic freshness manifest consumed by the runtime.

Mental model:
  The manifest is a content-addressed handoff between authoring and startup.
  Each row binds one source, entry point, target, and fixed compiler command to
  one bytecode file; --check verifies those hashes without rewriting assets.

Glossary:
  Bake: Cold build-time conversion from HLSL source to executable DXIL bytes.
  Input hash: SHA-256 of the source hash plus every compiler input that can
    change generated bytecode.

Invariants:
  - Shader order, JSON key order, and output paths are stable across machines.
  - Warnings are errors and matrices are explicitly column-major.
  - The raytracing library keeps its existing reflect.rt.dxil convention.

Related:
  - tools/bake_shaders.bat
  - SkullbonezSource/Rendering/DX12/ShaderBytecodeManifest.cpp
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile


SDK_VERSION = "10.0.26100.0"
DXC_VERSION = "1.8.2502.11"
SHADER_MODEL = "6_0"
COMMON_FLAGS = ("-WX", "-Ges", "-O3", "-Zpc", "-Qstrip_debug")
RASTER_STAGES = (("vs", "main_vs"), ("ps", "main_ps"))


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def canonical_json(value: object) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode("utf-8")


def find_dxc() -> Path:
    override = os.environ.get("SKULLBONEZ_DXC")
    candidates = []
    if override:
        candidates.append(Path(override))
    program_files_x86 = os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)")
    candidates.append(Path(program_files_x86) / "Windows Kits" / "10" / "bin" / SDK_VERSION / "x64" / "dxc.exe")
    for candidate in candidates:
        if candidate.is_file():
            return candidate.resolve()
    raise SystemExit(
        "Pinned DXC was not found. Install Windows SDK 10.0.26100.0 or set "
        "SKULLBONEZ_DXC to its x64 dxc.exe."
    )


def verify_dxc(dxc: Path) -> str:
    result = subprocess.run([str(dxc), "--version"], capture_output=True, text=True, check=False)
    output = (result.stdout + result.stderr).strip()
    if result.returncode != 0 or DXC_VERSION not in output:
        raise SystemExit(f"DXC version mismatch: expected {DXC_VERSION}, got {output or '<no output>'}")
    return output.replace("\r\n", "\n")


def shader_jobs(shader_dir: Path) -> list[dict[str, str]]:
    sources = sorted(shader_dir.glob("*.hlsl"), key=lambda path: path.name.lower())
    jobs: list[dict[str, str]] = []
    for source in sources:
        if source.name == "reflect.rt.hlsl":
            continue
        if source.name == "generate_mips.hlsl":
            stages = (("cs", "main_cs"),)
        else:
            stages = RASTER_STAGES
        for stage, entry in stages:
            jobs.append(
                {
                    "source": source.relative_to(shader_dir.parent.parent).as_posix(),
                    "entry": entry,
                    "stage": stage,
                    "target": f"{stage}_{SHADER_MODEL}",
                    "bytecode": source.with_suffix(f".{stage}.dxil").relative_to(shader_dir.parent.parent).as_posix(),
                }
            )
    return jobs


def compile_job(repo: Path, dxc: Path, job: dict[str, str], output: Path) -> bytes:
    args = [
        str(dxc),
        "-T",
        job["target"],
        "-E",
        job["entry"],
        *COMMON_FLAGS,
        "-Fo",
        str(output),
        job["source"],
    ]
    result = subprocess.run(args, cwd=repo, capture_output=True, text=True, check=False)
    diagnostics = (result.stdout + result.stderr).strip()
    if result.returncode != 0 or diagnostics:
        detail = diagnostics or f"DXC exited {result.returncode} without diagnostics"
        raise SystemExit(f"Shader bake failed for {job['source']} {job['stage']}:\n{detail}")
    return output.read_bytes()


def build_manifest(repo: Path, dxc: Path, version_text: str, check_only: bool) -> dict[str, object]:
    shader_dir = repo / "SkullbonezData" / "shaders"
    entries: list[dict[str, object]] = []
    for job in shader_jobs(shader_dir):
        source_bytes = (repo / job["source"]).read_bytes()
        source_hash = sha256_bytes(source_bytes)
        bytecode_path = repo / job["bytecode"]

        if check_only:
            if not bytecode_path.is_file():
                raise SystemExit(f"Missing baked shader: {job['bytecode']}")
            bytecode = bytecode_path.read_bytes()
            compile_args = [
                "-T", job["target"], "-E", job["entry"], *COMMON_FLAGS,
                "-Fo", "<output>", job["source"],
            ]
        else:
            with tempfile.TemporaryDirectory(prefix="skullbonez-shaders-") as temp_dir:
                temp_output = Path(temp_dir) / Path(job["bytecode"]).name
                bytecode = compile_job(repo, dxc, job, temp_output)
                compile_args = [
                    "-T", job["target"], "-E", job["entry"], *COMMON_FLAGS,
                    "-Fo", "<output>", job["source"],
                ]
            bytecode_path.write_bytes(bytecode)

        compile_inputs = {
            "compiler": f"Windows SDK {SDK_VERSION} DXC {DXC_VERSION}",
            "args": compile_args,
            "source_sha256": source_hash,
        }
        entry = dict(job)
        entry.update(
            {
                "source_sha256": source_hash,
                "compile_inputs_sha256": sha256_bytes(canonical_json(compile_inputs)),
                "bytecode_sha256": sha256_bytes(bytecode),
                "bytecode_size": len(bytecode),
            }
        )
        entries.append(entry)

    return {
        "format": 1,
        "compiler": {
            "sdk": SDK_VERSION,
            "dxc": DXC_VERSION,
            "reported_version": version_text,
        },
        "matrix_packing": "column_major",
        "common_flags": list(COMMON_FLAGS),
        "shader_model": f"6.{SHADER_MODEL[-1]}",
        "entries": entries,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Bake or verify Skullbonez DXIL shader assets.")
    parser.add_argument("--check", action="store_true", help="Verify checked-in DXIL and manifest freshness.")
    args = parser.parse_args()

    repo = Path(__file__).resolve().parent.parent
    manifest_path = repo / "SkullbonezData" / "shaders" / "shader_manifest.json"
    dxc = find_dxc()
    version_text = verify_dxc(dxc)
    manifest = build_manifest(repo, dxc, version_text, args.check)
    manifest_bytes = json.dumps(manifest, indent=2, ensure_ascii=True).encode("utf-8") + b"\n"

    if args.check:
        if not manifest_path.is_file() or manifest_path.read_bytes() != manifest_bytes:
            raise SystemExit("Shader manifest is stale; run tools\\bake_shaders.bat and commit the generated assets.")
        print(f"Shader bake freshness PASS: {len(manifest['entries'])} stages, DXC {DXC_VERSION}.")
        return 0

    manifest_path.write_bytes(manifest_bytes)
    print(f"Shader bake PASS: wrote {len(manifest['entries'])} stages with DXC {DXC_VERSION}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
