#pragma once

#include "../../../UI/UITooltip.h"
#include "../../Interaction/OperatorUiCommands.h"

namespace SkullbonezCore::UI
{
// Lifetime: static parameter help can be retained by the delayed tooltip.
// Array order follows the command enums; Sky reuses the same cinematic entries.
inline constexpr UITooltipText kRenderTooltipText[] = {
    { "Set the strength of direct sunlight.", "Intensity multiplier" },
    { "Set the red component of direct sunlight.", "Linear colour component" },
    { "Set the green component of direct sunlight.", "Linear colour component" },
    { "Set the blue component of direct sunlight.", "Linear colour component" },
    { "Set ambient light strength.", "Intensity multiplier" },
    { "Set the red component of sky illumination.", "Linear colour component" },
    { "Set the green component of sky illumination.", "Linear colour component" },
    { "Set the blue component of sky illumination.", "Linear colour component" },
    { "Set the red component of ground illumination.", "Linear colour component" },
    { "Set the green component of ground illumination.", "Linear colour component" },
    { "Set the blue component of ground illumination.", "Linear colour component" },
    { "Set the strength of rendered shadows.", "0 to 1" },
    { "Set shadow-edge softness.", "Filter scale" },
    { "Adjust shadow depth bias to reduce self-shadow artifacts.", "Depth bias" },
    { "Adjust shadow slope bias to reduce surface-angle artifacts.", "Slope bias" },
    { "Set the red component of water tint.", "Linear colour component" },
    { "Set the green component of water tint.", "Linear colour component" },
    { "Set the blue component of water tint.", "Linear colour component" },
    { "Set water opacity.", "0 transparent to 1 opaque" },
    { "Set water reflection strength.", "0 to 1" },
    { "Set water reflectance when viewed straight on.", "Fresnel F0" },
    { "Set sphere surface roughness.", "Roughness scale" },
    { "Set sphere specular strength.", "Intensity multiplier" },
    { "Set box surface roughness.", "Roughness scale" },
    { "Set box specular strength.", "Intensity multiplier" },
    { "Set the width of future prediction paths.", "Pixels" },
    { "Set the opacity of future prediction paths.", "0 transparent to 1 opaque" },
    { "Soften the edges of future prediction paths.", "Pixels" },
    { "Set the width of causal paths.", "Pixels" },
    { "Set the opacity of causal paths.", "0 transparent to 1 opaque" },
    { "Soften the edges of causal paths.", "Pixels" },
    { "Set the width of baseline paths.", "Pixels" },
    { "Set the opacity of baseline paths.", "0 transparent to 1 opaque" },
    { "Soften the edges of baseline paths.", "Pixels" },
    { "Set the width of marker paths.", "Pixels" },
    { "Set the opacity of marker paths.", "0 transparent to 1 opaque" },
    { "Soften the edges of marker paths.", "Pixels" },
    { "Set additional emphasis for selected paths.", "0 to 1" },
};
static_assert( sizeof( kRenderTooltipText ) / sizeof( kRenderTooltipText[0] ) == static_cast<int>( UIRenderParam::Count ) );

inline constexpr UITooltipText kCinematicTooltipText[] = {
    { "Set exposure before tone mapping.", "Exposure multiplier" },
    { "Set output gamma.", "Gamma exponent" },
    { "Select the authored sky style.", "Style index" },
    { "Select the authored terrain style.", "Style index" },
    { "Select the authored object style.", "Style index" },
    { "Select the authored water style.", "Style index" },
    { "Set overall colour saturation.", "Saturation multiplier" },
    { "Set overall image contrast.", "Contrast multiplier" },
    { "Darken the edges of the image.", "Vignette strength" },
    { "Set the sun direction around the horizon.", "Normalized azimuth, 0 to 1" },
    { "Set the sun height above the horizon.", "Normalized elevation, 0 to 1" },
    { "Set sun brightness.", "Intensity multiplier" },
    { "Set the red component of the sun colour.", "Linear colour component" },
    { "Set the green component of the sun colour.", "Linear colour component" },
    { "Set the blue component of the sun colour.", "Linear colour component" },
    { "Set glow around the sun.", "Glow strength" },
    { "Set the red component of the horizon colour.", "Linear colour component" },
    { "Set the green component of the horizon colour.", "Linear colour component" },
    { "Set the blue component of the horizon colour.", "Linear colour component" },
    { "Set the red component of the zenith colour.", "Linear colour component" },
    { "Set the green component of the zenith colour.", "Linear colour component" },
    { "Set the blue component of the zenith colour.", "Linear colour component" },
    { "Set how much of the sky is covered by clouds.", "Coverage" },
    { "Set the softness of cloud edges.", "Softness" },
    { "Set the cloud pattern scale.", "Scale multiplier" },
    { "Set cloud brightness.", "Intensity multiplier" },
    { "Set screen-space light shaft strength.", "Intensity multiplier" },
    { "Set light shaft falloff.", "Falloff" },
    { "Set volumetric light strength.", "Intensity multiplier" },
    { "Set volumetric light density.", "Density" },
    { "Set volumetric light decay.", "Decay" },
    { "Set the brightness threshold for bloom.", "Linear brightness" },
    { "Set the softness of the bloom threshold.", "Knee" },
    { "Set bloom strength.", "Intensity multiplier" },
    { "Set bloom blur radius.", "Filter scale" },
    { "Set the strength of rendered terrain relief.", "Relief scale" },
    { "Set the red component of terrain base tint.", "Linear colour component" },
    { "Set the green component of terrain base tint.", "Linear colour component" },
    { "Set the blue component of terrain base tint.", "Linear colour component" },
    { "Set the red component of terrain accent tint.", "Linear colour component" },
    { "Set the green component of terrain accent tint.", "Linear colour component" },
    { "Set the blue component of terrain accent tint.", "Linear colour component" },
    { "Set the terrain grid scale.", "Scale" },
    { "Set terrain grid visibility.", "Intensity multiplier" },
    { "Set the red component of cinematic water tint.", "Linear colour component" },
    { "Set the green component of cinematic water tint.", "Linear colour component" },
    { "Set the blue component of cinematic water tint.", "Linear colour component" },
    { "Set cinematic water opacity.", "0 transparent to 1 opaque" },
    { "Set cinematic water reflection strength.", "0 to 1" },
    { "Set water surface glint strength.", "Intensity multiplier" },
    { "Move the water basin centre along X.", "World units" },
    { "Move the water basin centre along Z.", "World units" },
    { "Set the water basin radius along X.", "World units" },
    { "Set the water basin radius along Z.", "World units" },
    { "Set the softness of the basin boundary.", "0 to 1" },
    { "Set basin depth.", "World units" },
    { "Set basin rim height.", "World units" },
    { "Set distance fog density.", "Density" },
    { "Set maximum fog opacity.", "0 transparent to 1 opaque" },
    { "Set the distance where fog begins.", "World units" },
    { "Set the far fog distance.", "World units" },
    { "Set the red component of fog.", "Linear colour component" },
    { "Set the green component of fog.", "Linear colour component" },
    { "Set the blue component of fog.", "Linear colour component" },
};
static_assert( sizeof( kCinematicTooltipText ) / sizeof( kCinematicTooltipText[0] ) ==
               static_cast<int>( UICinematicParam::Count ) );

inline constexpr UITooltipText kCinematicFeatureTooltipText[] = {
    { "Show or hide the cinematic sky.", "" },
    { "Show or hide cinematic clouds.", "" },
    { "Enable or disable screen-space light shafts.", "" },
    { "Enable or disable volumetric lighting.", "" },
    { "Enable or disable bloom around bright areas.", "" },
    { "Enable or disable distance fog.", "" },
    { "Enable or disable rendered terrain relief.", "" },
    { "Enable or disable cinematic shadows.", "" },
};
static_assert( sizeof( kCinematicFeatureTooltipText ) / sizeof( kCinematicFeatureTooltipText[0] ) ==
               static_cast<int>( UICinematicFeature::Count ) );

} // namespace SkullbonezCore::UI
